name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: "Setup"
      id: setup
      run: date -u "+::set-output name=date::%FT%T"

    - name: "Caching"
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.XML2RFC_REFCACHEDIR }}
          ${{ env.VENVDIR }}
          ${{ env.BUNDLE_PATH }}
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload

    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v2
      with:
        path: "draft-*-[0-9][0-9].xml"
